<?php

namespace AppBundle\Repository;

/**
 * BorneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorneRepository extends \Doctrine\ORM\EntityRepository
{
}
