<?php

namespace AppBundle\Repository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends \Doctrine\ORM\EntityRepository
{
}
